service: React-Real-Estate-Website
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: 20201221
  region: ${env:REACT_APP_AWS_REGION}
  environment:
    AWS_ACCESS_KEY_ID: ${env:REACT_APP_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:REACT_APP_AWS_SECRET_ACCESS_KEY}
    
    

package:
  individually: false
  excludeDevDependencies: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**


functions:
  site:
    handler: ./src/App.handler
    events:
      - http:
          path: /
          method: ANY


plugins:
  - serverless-dotenv-plugin